### ISSUE TITLE
error: option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by ChetanTomar** [sethblack/python-seo-analyzer#18]
```
chetan@chetan-Inspiron-3542:~/Desktop$ sudo pip3 install -U  pyseoanalyzer
The directory '/home/chetan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/chetan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyseoanalyzer
  Downloading pyseoanalyzer-3.0.5.tar.gz
Requirement already up-to-date: BeautifulSoup4 in /usr/local/lib/python3.4/dist-packages (from pyseoanalyzer)
Requirement already up-to-date: nltk in /usr/local/lib/python3.4/dist-packages (from pyseoanalyzer)
Requirement already up-to-date: numpy in /usr/local/lib/python3.4/dist-packages (from pyseoanalyzer)
Requirement already up-to-date: requests in /usr/local/lib/python3.4/dist-packages (from pyseoanalyzer)
Requirement already up-to-date: jinja2 in /usr/local/lib/python3.4/dist-packages (from pyseoanalyzer)
Requirement already up-to-date: six in /usr/local/lib/python3.4/dist-packages (from nltk->pyseoanalyzer)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.4/dist-packages (from requests->pyseoanalyzer)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.4/dist-packages (from requests->pyseoanalyzer)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.4/dist-packages (from requests->pyseoanalyzer)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.4/dist-packages (from requests->pyseoanalyzer)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python3.4/dist-packages (from jinja2->pyseoanalyzer)
Installing collected packages: pyseoanalyzer
  Running setup.py install for pyseoanalyzer ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6d9pf_nh/pyseoanalyzer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-g5lm90ji-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized

```

**Comment by sethblack** [comment]
Heyo @ChetanTomar what version of pip and setuptools do you have? --single-version-externally-managed was added quite a while back.

**Comment by ChetanTomar** [comment]
@sethblack, 

`pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)`

**Comment by N2ITN** [comment]
I am on python 3.5, latest pip, same error.

```Installing collected packages: pyseoanalyzer, certifi
  Running setup.py install for pyseoanalyzer ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ytnc6up9/pyseoanalyzer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h45vjewz-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ytnc6up9/pyseoanalyzer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h45vjewz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ytnc6up9/pyseoanalyzer/
```

**Comment by rtruxal** [comment]
This is a linux problem.  
Here's 3.6 on debian:
```
...
...
...
running install_egg_info
  Copying pyseoanalyzer.egg-info to build/bdist.linux-x86_64/wheel/pyseoanalyzer-3.0.5-py3.6.egg-info
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-u8xg3bcq/pyseoanalyzer/setup.py", line 55, in <module>
      """
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/my_username/anaconda2/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-u8xg3bcq/pyseoanalyzer/setup.py", line 11, in run
      import nltk
  ModuleNotFoundError: No module named 'nltk'

  ----------------------------------------
  Failed building wheel for pyseoanalyzer
  Running setup.py clean for pyseoanalyzer
  Running setup.py bdist_wheel for nltk ... done
  Stored in directory: /home/my_username/.cache/pip/wheels/18/9c/1f/276bc3f421614062468cb1c9d695e6086d0c73d67ea363c501
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /home/my_username/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built nltk MarkupSafe
Failed to build pyseoanalyzer
Installing collected packages: BeautifulSoup4, nltk, certifi, chardet, urllib3, idna, requests, MarkupSafe, jinja2, pyseoanalyzer
  Running setup.py install for pyseoanalyzer ... error
    Complete output from command /home/my_username/anaconda2/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u8xg3bcq/pyseoanalyzer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-obn9l569-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/home/my_username/anaconda2/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u8xg3bcq/pyseoanalyzer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-obn9l569-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-u8xg3bcq/pyseoanalyzer/
```
