### ISSUE TITLE
`seoanalyze -f html https://www.foo-site.bar` throws Jinja2 Loader Error

### ISSUE THREAD

**Issue by rtruxal** [sethblack/python-seo-analyzer#24]
Gotta love Jinja2 errors!!
```
λ seoanalyze -f html https://landing.bscg.us
Traceback (most recent call last):
  File "c:\anaconda2\envs\py36test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda2\envs\py36test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda2\envs\py36test\Scripts\seoanalyze.exe\__main__.py", line 9, in <module>
  File "c:\anaconda2\envs\py36test\lib\site-packages\seoanalyzer\__main__.py", line 33, in main
    template = env.get_template('index.html')
  File "c:\anaconda2\envs\py36test\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\anaconda2\envs\py36test\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\anaconda2\envs\py36test\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\anaconda2\envs\py36test\lib\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```
`TemplateNotFound` can only mean ~3 things. & I think I know which one it is based on:

```
File "c:\anaconda2\envs\py36test\lib\site-packages\seoanalyzer\__main__.py", line 33, in main
    template = env.get_template('index.html')
```
Let me know if anyone else is getting this error!

Otherwise, I'll probably have a fixing pull-req out by EoD.

**Comment by rtruxal** [comment]
I am going to fix this lol.

**Comment by llazzaro** [comment]
I have the same error today. If you execute with cloned repo it works

**Comment by rtruxal** [comment]
Hey so when you say "I have the same error today." You mean when you install from pypi via:
```
~$ pip install pyseoanalyzer
```
Right?

**Comment by rtruxal** [comment]
@llazzaro - I just spoke with @sethblack & he's going to push `3.1.1` to pypi tonight. 

Can you check again tomorrow and let us know if it's working?
