### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by kamal2222ahmed** [sethblack/python-seo-analyzer#35]
I tried to run this on Mac:

seoanalyze http://www.benefits.gov
Traceback (most recent call last):
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ashbbcpsg03.usae.bah.com', port=4433): Max retries exceeded with url: /?cfru=aHR0cDovL3d3dy5iZW5lZml0cy5nb3Yv (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/syedahmed/anaconda3/bin/seoanalyze", line 11, in <module>
    sys.exit(main())
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/seoanalyzer/__main__.py", line 26, in main
    output = analyze(args.site, args.sitemap)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/seoanalyzer/analyzer.py", line 622, in analyze
    pg.analyze()
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/seoanalyzer/analyzer.py", line 243, in analyze
    page = self.session.get(self.url)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 222, in resolve_redirects
    **adapter_kwargs
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ashbbcpsg03.usae.bah.com', port=4433): Max retries exceeded with url: /?cfru=aHR0cDovL3d3dy5iZW5lZml0cy5nb3Yv (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])")))

**Comment by TheWebGuruDotNet** [comment]
try to add the SSL to your domain request (HTTPS):
seoanalyze https://www.benefits.gov
