### ISSUE TITLE
Not working with 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)

### ISSUE THREAD

**Issue by rickosteen** [sethblack/python-seo-analyzer#39]
FYI

error output below:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/seoanalyze", line 11, in <module>
    load_entry_point('pyseoanalyzer==3.1.1', 'console_scripts', 'seoanalyze')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/seoanalyzer/__main__.py", line 33, in main
    template = env.get_template('index.html')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

**Comment by rickosteen** [comment]
pip3 list

Package          Version  
---------------- ---------
altgraph         0.16.1   
asn1crypto       0.24.0   
attrs            19.1.0   
Automat          0.7.0    
beautifulsoup4   4.8.0    
bs4              0.0.1    
certifi          2019.6.16
cffi             1.12.3   
chardet          3.0.4    
constantly       15.1.0   
cryptography     2.7      
cssselect        1.1.0    
hyperlink        19.0.0   
idna             2.8      
incremental      17.5.0   
Jinja2           2.10.1   
lxml             4.4.1    
macholib         1.11     
MarkupSafe       1.1.1    
parsel           1.5.2    
pip              19.2.2   
pyasn1           0.4.6    
pyasn1-modules   0.2.6    
pycparser        2.19     
PyDispatcher     2.0.5    
PyHamcrest       1.9.0    
PyInstaller      3.5      
PyOanda          1.22     
pyOpenSSL        19.0.0   
pyseoanalyzer    3.1.1    
queuelib         1.5.0    
requests         2.22.0   
Scrapy           1.7.3    
service-identity 18.1.0   
setuptools       40.8.0   
six              1.12.0   
soupsieve        1.9.2    
Twisted          19.7.0   
urllib3          1.25.3   
w3lib            1.21.0   
zope.interface   4.6.0

**Comment by rickosteen** [comment]
I notice some notes stating it was working with urllib2 and python 3.6. 

I wish I could help more but my programming skills are novice at this point.

**Comment by sethblack** [comment]
Heyo. Sorry for this crazy delay. This should be fixed in version 3.1.2. Let me know if you're still seeing issues.
