### ISSUE TITLE
InvalidSchema: javascript event code in href

### ISSUE THREAD

**Issue by michaelnguy** [sethblack/python-seo-analyzer#47]
I ran the analyzer on a website and got this error. Anyway to filter these urls?

Traceback (most recent call last):
  File "...\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\Python37-32\Scripts\seoanalyze.exe\__main__.py", line 7, in <module>
  File "...\python37-32\lib\site-packages\seoanalyzer\__main__.py", line 26, in main
    output = analyze(args.site, args.sitemap)
  File "...\python37-32\lib\site-packages\seoanalyzer\analyzer.py", line 618, in analyze
    pg.analyze()
  File "...\python37-32\lib\site-packages\seoanalyzer\analyzer.py", line 239, in analyze
    page = self.session.get(self.url)
  File "...\python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "...\python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "...\python37-32\lib\site-packages\requests\sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "...\python37-32\lib\site-packages\requests\sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'javascript:poptastic('http://www.website.com/share.php?...');'

**Comment by sethblack** [comment]
Hiya! I just patched it in version 3.1.4 to ignore javascript links, that should unblock you for now.
