### ISSUE TITLE
ImportError: cannot import name 'PoolManager' from 'urllib3'

### ISSUE THREAD

**Issue by manik987** [sethblack/python-seo-analyzer#69]
**Describe the bug**
Not working ...

**Expected behavior**
still not working after fixinf urllib3 

python analyzer.py https://www.sethserver.com/ -f html > results.html
Traceback (most recent call last):
  File "analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\__init__.py", line 3, in <module>
    from .analyzer import analyze
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\website.py", line 8, in <module>
    from seoanalyzer.http import http
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\seoanalyzer\http.py", line 2, in <module>
    import urllib3
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:\Users\Manik Malhotra\Downloads\python-seo-analyzer-master (5)\python-seo-analyzer-master\seoanalyzer\http.py", line 2, in <module>
    from urllib3 import PoolManager
ImportError: cannot import name 'PoolManager' from 'urllib3' (C:\Users\Manik Malhotra\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\__init__.py)

**Desktop (please complete the following information):**
 - OS:windows 10
 - Browser [ edge
 - Version 4.04

**Comment by sethblack** [comment]
It's ok to keep the conversation going on the previous bug.

**Comment by manik987** [comment]
ok
