### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by hapesurya** [sethblack/python-seo-analyzer#82]
I use Python 3.8.10
I use virtual environment to run your script
I check my web already have index.xml

When i run it from terminal :

seoanalyze http://www.domain.com/

or

seoanalyze http://www.domain.com/ --sitemap http://www.domain.com/sf2-sitemap/index.xml

it response :

Traceback (most recent call last):
File "...../my-venv/bin/seoanalyze", line 7, in <module>
    from seoanalyzer.__main__ import main
  File "...../my-venv/lib/python3.8/site-packages/seoanalyzer/__init__.py", line 3, in <module>
    from .analyzer import analyze
  File "...../my-venv/lib/python3.8/site-packages/seoanalyzer/analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "...../my-venv/lib/python3.8/site-packages/seoanalyzer/website.py", line 9, in <module>
    from seoanalyzer.page import Page
  File "...../my-venv/lib/python3.8/site-packages/seoanalyzer/page.py", line 8, in <module>
    import lxml.html as lh
ModuleNotFoundError: No module named 'lxml'

Need your help. Many thanks.

**Comment by j-masci** [comment]
pip install lxml worked for me, is there something i'm missing here?

**Comment by sethblack** [comment]
Hmm, strange. Yeah, looks like lxml disappeared from the dependencies; but it's still in the requirements.txt. I'll get that updated and pushed out with the next version.

The temporary workaround is exactly what @j-masci said, installing lxml into your virtual environment will fix the issue.
